package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Admins generated by hbm2java
 */
@Entity(name = "admins")
@Table(name="admins"
    ,catalog="ecomm"
)
public class Admins  implements java.io.Serializable {


     private String email;
     private String password;

    public Admins() {
    }

    public Admins(String email, String password) {
       this.email = email;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=270)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


