package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdminRoles generated by hbm2java
 */
@Entity
@Table(name="admin_roles"
    ,catalog="ecomm"
)
public class AdminRoles  implements java.io.Serializable {


     private AdminRolesId id;

    public AdminRoles() {
    }

    public AdminRoles(AdminRolesId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false, length=45) ), 
        @AttributeOverride(name="role", column=@Column(name="role", nullable=false, length=45) ) } )
    public AdminRolesId getId() {
        return this.id;
    }
    
    public void setId(AdminRolesId id) {
        this.id = id;
    }




}


