package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CartItems generated by hbm2java
 */
@Entity
@Table(name="cart_items"
    ,catalog="ecomm"
)
public class CartItems  implements java.io.Serializable {


     private CartItemsId id;
     private Products products;
     private Customers customers;
     private int quantity;

    public CartItems() {
    }

    public CartItems(CartItemsId id, Products products, Customers customers, int quantity) {
       this.id = id;
       this.products = products;
       this.customers = customers;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="customerId", column=@Column(name="customer_id", nullable=false) ), 
        @AttributeOverride(name="prodId", column=@Column(name="prod_id", nullable=false) ) } )
    public CartItemsId getId() {
        return this.id;
    }
    
    public void setId(CartItemsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="prod_id", nullable=false, insertable=false, updatable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false, insertable=false, updatable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


