package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="ecomm"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="name")} 
)
public class Customers  implements java.io.Serializable {


     private Integer customerId;
     private String name;
     private String email;
     private String password;
     private String address;
     private Date regDate;
     private double credit;
     private String image;
     private String phone;
     private Set<Orders> orderses = new HashSet<Orders>(0);
     private Set<CartItems> cartItemses = new HashSet<CartItems>(0);

    public Customers() {
    }

	
    public Customers(String name, String email, String password, Date regDate, double credit, String image) {
        this.name = name;
        this.email = email;
        this.password = password;
        this.regDate = regDate;
        this.credit = credit;
        this.image = image;
    }
    public Customers(String name, String email, String password, String address, Date regDate, double credit, String image, String phone, Set<Orders> orderses, Set<CartItems> cartItemses) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.address = address;
       this.regDate = regDate;
       this.credit = credit;
       this.image = image;
       this.phone = phone;
       this.orderses = orderses;
       this.cartItemses = cartItemses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="name", unique=true, nullable=false, length=25)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=270)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reg_date", nullable=false, length=19)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    
    @Column(name="credit", nullable=false, precision=22, scale=0)
    public double getCredit() {
        return this.credit;
    }
    
    public void setCredit(double credit) {
        this.credit = credit;
    }

    
    @Column(name="image", nullable=false, length=250)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<CartItems> getCartItemses() {
        return this.cartItemses;
    }
    
    public void setCartItemses(Set<CartItems> cartItemses) {
        this.cartItemses = cartItemses;
    }




}


