package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FeaturedProds generated by hbm2java
 */
@Entity(name = "featuredprods")
@Table(name="featured_prods"
    ,catalog="ecomm"
)
public class FeaturedProds  implements java.io.Serializable {


     private Integer featuredProdId;
     private Products products;

    public FeaturedProds() {
    }

    public FeaturedProds(Products products) {
       this.products = products;
    }
   
     @GenericGenerator(name="FeaturedProdsIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="products"))@Id @GeneratedValue(generator="FeaturedProdsIdGenerator")

    
    @Column(name="featured_prod_id", unique=true, nullable=false)
    public Integer getFeaturedProdId() {
        return this.featuredProdId;
    }
    
    public void setFeaturedProdId(Integer featuredProdId) {
        this.featuredProdId = featuredProdId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }




}


