package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name="order_items"
    ,catalog="ecomm"
)
public class OrderItems  implements java.io.Serializable {


     private Integer orderItemId;
     private Orders orders;
     private int prodId;
     private Integer quantity;
     private Double unitPrice;

    public OrderItems() {
    }

	
    public OrderItems(Orders orders, int prodId) {
        this.orders = orders;
        this.prodId = prodId;
    }
    public OrderItems(Orders orders, int prodId, Integer quantity, Double unitPrice) {
       this.orders = orders;
       this.prodId = prodId;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_item_id", unique=true, nullable=false)
    public Integer getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(Integer orderItemId) {
        this.orderItemId = orderItemId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="prod_id", nullable=false)
    public int getProdId() {
        return this.prodId;
    }
    
    public void setProdId(int prodId) {
        this.prodId = prodId;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="unit_price", precision=22, scale=0)
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }




}


