package org.iti.db.domain;// default package
// Generated Mar 23, 2021, 6:50:21 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name="payments"
    ,catalog="ecomm"
)
public class Payments  implements java.io.Serializable {


     private Integer paymentId;
     private Orders orders;
     private double amount;
     private String method;
     private String txCode;

    public Payments() {
    }

    public Payments(Orders orders, double amount, String method, String txCode) {
       this.orders = orders;
       this.amount = amount;
       this.method = method;
       this.txCode = txCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

    
    @Column(name="amount", nullable=false, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="method", nullable=false, length=45)
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }

    
    @Column(name="tx_code", nullable=false, length=200)
    public String getTxCode() {
        return this.txCode;
    }
    
    public void setTxCode(String txCode) {
        this.txCode = txCode;
    }




}


